Examen/UI.Web/Models/ErrorViewModel.cs
namespace UI.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen/UI.Web/Controllers/AvocatController.cs
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace UI.Web.Controllers
{
    public class AvocatController : Controller
    {
        IServiceAvocat serviceAvocat;

        public AvocatController(IServiceAvocat serviceAvocat)
        {
            this.serviceAvocat = serviceAvocat;
        }

        // GET: AvocatController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AvocatController/Details/5
        public ActionResult Details(int id)
        {
            return View(serviceAvocat.GetById(id));
        }

        // GET: AvocatController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AvocatController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AvocatController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AvocatController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AvocatController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AvocatController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen/UI.Web/Controllers/DossierController.cs
using ApplicationCore.Domain;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace UI.Web.Controllers
{
    public class DossierController : Controller
    {
        IDossierService serviceDossier;
        IServiceAvocat serviceAvocat;
        IServiceClient serviceClient;

        public DossierController(IDossierService serviceDossier, IServiceAvocat serviceAvocat,
        IServiceClient serviceClient)
        {
            this.serviceDossier = serviceDossier;
            this.serviceClient = serviceClient;
            this.serviceAvocat = serviceAvocat;
        }

        // GET: DossierController
        public ActionResult Index(string nomSearch)
        {
            if (nomSearch == null)
            {
                return View(serviceDossier.GetMany());
            }
            else
                return View(serviceDossier.GetMany(c => c.Avocat.Nom.Contains(nomSearch)));
        }

        // GET: DossierController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DossierController/Create
        public ActionResult Create()
        {
            ViewBag.listClient = new SelectList(serviceClient.GetMany(), "CIN", "Nom");
            ViewBag.listAvocat = new SelectList(serviceAvocat.GetMany(), "AvocatId", "Nom");


            return View();
        }

        // POST: DossierController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dossier collection)
        {
            try
            {
                serviceDossier.Add(collection);
                    serviceDossier.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DossierController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DossierController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DossierController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DossierController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen/UI.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UI.Web.Models;

namespace UI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Examen/UI.Web/Views/Avocat/Details.cshtml
@model ApplicationCore.Domain.Avocat

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Avocat</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvocatId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvocatId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEmbauche)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEmbauche)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpecialiteFK)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpecialiteFK)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Examen/UI.Web/Views/Dossier/Create.cshtml
@model ApplicationCore.Domain.Dossier

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Dossier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateDepot" class="control-label"></label>
                <input asp-for="DateDepot" class="form-control" />
                <span asp-validation-for="DateDepot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <textarea asp-for="description" class="form-control"></textarea>
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="frais" class="control-label"></label>
                <input asp-for="frais" class="form-control" />
                <span asp-validation-for="frais" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="clos" /> @Html.DisplayNameFor(model => model.clos)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Avocat_FK" class="control-label"></label>
                <select asp-for="Avocat_FK" asp-items=ViewBag.listAvocat class="form-control"></select>
                <span asp-validation-for="Avocat_FK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Client_FK" class="control-label"></label>
                <select asp-for="Client_FK" asp-items=ViewBag.listClient class="form-control"></select>
                <span asp-validation-for="Client_FK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen/UI.Web/Views/Dossier/Index.cshtml
@model IEnumerable<ApplicationCore.Domain.Dossier>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<form asp-action="index">

<fieldset>
    <legend> Recherche</legend>
    Saisir un login :
    <input type="text" name="nomSearch" />
    <input type="submit" value="Search" />

</fieldset>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateDepot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.frais)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.clos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Avocat_FK)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client_FK)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateDepot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.frais)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.clos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Avocat_FK)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client_FK)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    <a asp-controller="Avocat" asp-action="Details" asp-route-id="@item.Avocat_FK">avocatdetail</a>

            </td>
        </tr>
}
    </tbody>
</table>

Examen/UI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Examen/UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UI.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>